---
title: "pheatmaps (smoking)"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning = FALSE, message = FALSE}
library(phyloseq)
library(compositions)
library(pheatmap)
library(RColorBrewer)
```

### Load phyloseq data and smoking samples

```{r, echo=TRUE}
# set working directory
setwd('/Users/alicesommer/Desktop/Bureau/DOCTORATE')
# load microbiome data
ASV_table <- readRDS('data_pipeline_microbiome/dada2output/seqtab2020.rds')
taxon_assign <- readRDS('data_pipeline_microbiome/dada2output/taxa2020.rds')

# load sample/matched_data
load('data_pipeline_microbiome/dat_matched_smoke_bis.RData')

sample_df <- matched_df[order(matched_df$ff4_prid),]
sample_df$W <- as.factor(sample_df$W)
samples.out <- as.character(sample_df$ff4_prid)
rownames(sample_df) <- samples.out

# create a phyloseq object
ps <- phyloseq(otu_table(ASV_table, taxa_are_rows=FALSE),
               sample_data(sample_df),
               tax_table(taxon_assign))
ps

# remove the ASVs never observed in the matched samples
vec_taxa <- apply(otu_table(ps), 2, function(x) sum(x > 0, na.rm = TRUE))
ps <- prune_taxa(vec_taxa > 0, ps)
```

## Phylum level

```{r, echo=FALSE}
# clr transform data
level <- "Phylum"
ps_agg <- tax_glom(ps, taxrank = level, NArm = FALSE)
ps_work <- transform_sample_counts(ps_agg, function(x) {clr(x + .5)})

X <- as(otu_table(ps_work), "matrix") # unname to remove sequences as "title"
X[otu_table(ps_agg) == 0] <- 0 # replace the pseudo-counted zeros to zeros again
```

```{r, echo=FALSE, fig.height=6, fig.width=22}
X_split <- X[order(sample_data(ps_work)$W),]

data.prop <- t(X_split)
rownames(data.prop) <- tax_table(ps_work)[,level]

# Data frame with column annotations.
new_W <- sample_data(ps_work)$W[order(sample_data(ps_work)$W)]
mat_col <- data.frame(W = as.factor(new_W))
rownames(mat_col) <- colnames(data.prop)

# List with colors for each annotation.
mat_colors <- list(group = brewer.pal(3, "Set1"))
names(mat_colors$group) <- unique(sample_df$W)

pheatmap(
  mat               = data.prop,
  # color             = inferno(length(mat_breaks) - 1),
  # border_color      = NA,
  gaps_col = length(new_W)/2,
  cluster_rows = TRUE,
  cluster_cols = FALSE,
  show_colnames     = FALSE,
  show_rownames     = TRUE,
  annotation_col    = mat_col,
  annotation_colors = list(W = c('0' = "#E41A1C", '1' = "#4DAF4A")),
  drop_levels       = FALSE,
  fontsize_row      = 14,
  cellwidth = 1.6
  # main              = ""
  # cutree_cols = 3
)
```

```{r, echo=FALSE, fig.height=6, fig.width=22}
pheatmap(
  mat               = data.prop,
  border_color      = NA,
  show_colnames     = FALSE,
  show_rownames     = TRUE,
  annotation_col    = mat_col,
  annotation_colors = list(W = c('0' = "#E41A1C", '1' = "#4DAF4A")),
  drop_levels       = TRUE,
  fontsize          = 14,
  cellwidth = 1.6,
  main              = ""
)
```

## Class level

```{r, echo=FALSE}
# clr transform data
level <- "Class"
ps_agg <- tax_glom(ps, taxrank = level, NArm = FALSE)
ps_work <- transform_sample_counts(ps_agg, function(x) {clr(x + .5)})

X <- as(otu_table(ps_work), "matrix") # unname to remove sequences as "title"
X[otu_table(ps_agg) == 0] <- 0 # replace the pseudo-counted zeros to zeros again
```

```{r, echo=FALSE, fig.height=8, fig.width=22}
X_split <- X[order(sample_data(ps_work)$W),]

data.prop <- t(X_split)
rownames(data.prop) <- tax_table(ps_work)[,level]

# Data frame with column annotations.
new_W <- sample_data(ps_work)$W[order(sample_data(ps_work)$W)]
mat_col <- data.frame(W = as.factor(new_W))
rownames(mat_col) <- colnames(data.prop)

# List with colors for each annotation.
mat_colors <- list(group = brewer.pal(3, "Set1"))
names(mat_colors$group) <- unique(sample_df$W)

pheatmap(
  mat               = data.prop,
  # color             = inferno(length(mat_breaks) - 1),
  # border_color      = NA,
  gaps_col = length(new_W)/2,
  cluster_rows = TRUE,
  cluster_cols = FALSE,
  show_colnames     = FALSE,
  show_rownames     = TRUE,
  annotation_col    = mat_col,
  annotation_colors = list(W = c('0' = "#E41A1C", '1' = "#4DAF4A")),
  drop_levels       = FALSE,
  fontsize_row      = 14,
  cellwidth = 1.6
  # main              = ""
  # cutree_cols = 3
)
```

```{r, echo=FALSE, fig.height=8, fig.width=22}
pheatmap(
  mat               = data.prop,
  border_color      = NA,
  show_colnames     = FALSE,
  show_rownames     = TRUE,
  annotation_col    = mat_col,
  annotation_colors = list(W = c('0' = "#E41A1C", '1' = "#4DAF4A")),
  drop_levels       = TRUE,
  fontsize          = 14,
  cellwidth = 1.6,
  main              = ""
)
```

## Order level

```{r, echo=FALSE}
# clr transform data
level <- "Order"
ps_agg <- tax_glom(ps, taxrank = level, NArm = FALSE)
ps_work <- transform_sample_counts(ps_agg, function(x) {clr(x + .5)})

X <- as(otu_table(ps_work), "matrix") # unname to remove sequences as "title"
X[otu_table(ps_agg) == 0] <- 0 # replace the pseudo-counted zeros to zeros again
```

```{r, echo=FALSE, fig.height=12, fig.width=22}
X_split <- X[order(sample_data(ps_work)$W),]

data.prop <- t(X_split)
rownames(data.prop) <- tax_table(ps_work)[,level]

# Data frame with column annotations.
new_W <- sample_data(ps_work)$W[order(sample_data(ps_work)$W)]
mat_col <- data.frame(W = as.factor(new_W))
rownames(mat_col) <- colnames(data.prop)

# List with colors for each annotation.
mat_colors <- list(group = brewer.pal(3, "Set1"))
names(mat_colors$group) <- unique(sample_df$W)

pheatmap(
  mat               = data.prop,
  # color             = inferno(length(mat_breaks) - 1),
  # border_color      = NA,
  gaps_col = length(new_W)/2,
  cluster_rows = TRUE,
  cluster_cols = FALSE,
  show_colnames     = FALSE,
  show_rownames     = TRUE,
  annotation_col    = mat_col,
  annotation_colors = list(W = c('0' = "#E41A1C", '1' = "#4DAF4A")),
  drop_levels       = FALSE,
  fontsize_row      = 14,
  cellwidth = 1.6
  # main              = ""
  # cutree_cols = 3
)
```

```{r, echo=FALSE, fig.height=12, fig.width=22}
pheatmap(
  mat               = data.prop,
  border_color      = NA,
  show_colnames     = FALSE,
  show_rownames     = TRUE,
  annotation_col    = mat_col,
  annotation_colors = list(W = c('0' = "#E41A1C", '1' = "#4DAF4A")),
  drop_levels       = TRUE,
  fontsize          = 14,
  cellwidth = 1.6,
  main              = ""
)
```

## Family level

```{r, echo=FALSE}
# clr transform data
level <- "Family"
ps_agg <- tax_glom(ps, taxrank = level, NArm = FALSE)
ps_work <- transform_sample_counts(ps_agg, function(x) {clr(x + .5)})

X <- as(otu_table(ps_work), "matrix") # unname to remove sequences as "title"
X[otu_table(ps_agg) == 0] <- 0 # replace the pseudo-counted zeros to zeros again
```

```{r, echo=FALSE, fig.height=20, fig.width=22}
X_split <- X[order(sample_data(ps_work)$W),]

data.prop <- t(X_split)
rownames(data.prop) <- tax_table(ps_work)[,level]

# Data frame with column annotations.
new_W <- sample_data(ps_work)$W[order(sample_data(ps_work)$W)]
mat_col <- data.frame(W = as.factor(new_W))
rownames(mat_col) <- colnames(data.prop)

# List with colors for each annotation.
mat_colors <- list(group = brewer.pal(3, "Set1"))
names(mat_colors$group) <- unique(sample_df$W)

pheatmap(
  mat               = data.prop,
  # color             = inferno(length(mat_breaks) - 1),
  # border_color      = NA,
  gaps_col = length(new_W)/2,
  cluster_rows = TRUE,
  cluster_cols = FALSE,
  show_colnames     = FALSE,
  show_rownames     = TRUE,
  annotation_col    = mat_col,
  annotation_colors = list(W = c('0' = "#E41A1C", '1' = "#4DAF4A")),
  drop_levels       = FALSE,
  fontsize_row      = 14,
  cellwidth = 1.6
  # main              = ""
  # cutree_cols = 3
)
```

```{r, echo=FALSE, fig.height=20, fig.width=22}
pheatmap(
  mat               = data.prop,
  border_color      = NA,
  show_colnames     = FALSE,
  show_rownames     = TRUE,
  annotation_col    = mat_col,
  annotation_colors = list(W = c('0' = "#E41A1C", '1' = "#4DAF4A")),
  drop_levels       = TRUE,
  fontsize          = 14,
  cellwidth = 1.6,
  main              = ""
)
```

## Genus level

```{r, echo=FALSE}
# clr transform data
level <- "Genus"
ps_agg <- tax_glom(ps, taxrank = level, NArm = FALSE)
ps_work <- transform_sample_counts(ps_agg, function(x) {clr(x + .5)})

X <- as(otu_table(ps_work), "matrix") # unname to remove sequences as "title"
X[otu_table(ps_agg) == 0] <- 0 # replace the pseudo-counted zeros to zeros again
```

```{r, echo=FALSE, fig.height=30, fig.width=22}
X_split <- X[order(sample_data(ps_work)$W),]

data.prop <- t(X_split)
rownames(data.prop) <- tax_table(ps_work)[,level]

# Data frame with column annotations.
new_W <- sample_data(ps_work)$W[order(sample_data(ps_work)$W)]
mat_col <- data.frame(W = as.factor(new_W))
rownames(mat_col) <- colnames(data.prop)

# List with colors for each annotation.
mat_colors <- list(group = brewer.pal(3, "Set1"))
names(mat_colors$group) <- unique(sample_df$W)

pheatmap(
  mat               = data.prop,
  # color             = inferno(length(mat_breaks) - 1),
  # border_color      = NA,
  gaps_col = length(new_W)/2,
  cluster_rows = TRUE,
  cluster_cols = FALSE,
  show_colnames     = FALSE,
  show_rownames     = TRUE,
  annotation_col    = mat_col,
  annotation_colors = list(W = c('0' = "#E41A1C", '1' = "#4DAF4A")),
  drop_levels       = FALSE,
  fontsize_row      = 10,
  cellwidth = 1.6
  # main              = ""
  # cutree_cols = 3
)
```

```{r, echo=FALSE, fig.height=30, fig.width=22}
pheatmap(
  mat               = data.prop,
  border_color      = NA,
  show_colnames     = FALSE,
  show_rownames     = TRUE,
  annotation_col    = mat_col,
  annotation_colors = list(W = c('0' = "#E41A1C", '1' = "#4DAF4A")),
  drop_levels       = TRUE,
  fontsize          = 10,
  cellwidth = 1.6,
  main              = ""
)
```

