---
title: "Networks viz Genus (pollution)"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## NetCoMi 

For more details on using the NetCoMi package see <https://github.com/stefpeschel/NetCoMi>.

```{r, echo=FALSE, message=FALSE, warning = FALSE}
library(NetCoMi)
library(metagMisc)
library(phyloseq)
library(igraph)
library(plyr)
library(ForceAtlas2)
library(pals)
library(RColorBrewer)
library(corrplot)
library(stringr)
```

## Networks comparison

The following code was run on a cluster.

```{r, echo = TRUE}
# # load phyloseq data
# load('/Users/alicesommer/Desktop/Bureau/DOCTORATE/data_pipeline_microbiome/ps_to_net_Gen.RData')
# 
# gut_split <- metagMisc::phyloseq_sep_variable(ps_Genus_prune, "W")
# 
# net_W <- netConstruct(gut_split$`0`, gut_split$`1`, verbose = 2,
#         # filtTax = "highestVar",
#         # filtTaxPar = list(highestVar = 50),
#                            measure = "spieceasi",
#                           measurePar = list(method = "glasso",
#                                             nlambda=20,
#                                             pulsar.params=list(rep.num=50)),
#                           normMethod = "none", zeroMethod = "none",
#                           sparsMethod = "none", seed = 123456, matchDesign = c(1,1))
# 
# 
# props_W <- netAnalyze(net_W, clustMethod = "cluster_fast_greedy", connectivity = FALSE)
# save(props_W, file = "/Users/alicesommer/Desktop/Bureau/DOCTORATE/data_pipeline_microbiome/props_W_Gen.RData")
```

```{r, echo=FALSE}
load('/Users/alicesommer/Desktop/Bureau/DOCTORATE/data_pipeline_microbiome/ps_to_net_Gen.RData')
load('/Users/alicesommer/Desktop/Bureau/DOCTORATE/data_pipeline_microbiome/props_W_Gen.RData')
```

```{r, echo=FALSE}
# which(tax_table(ps_Genus_prune)[,"Genus"] == "Marvinbryantia")

tax_table(ps_Genus_prune)[c(116,5,47),]
```

```{r}
# layout union of networks
graph1 <- graph_from_adjacency_matrix(props_W$input$adjaMat1, weighted = TRUE)
graph2 <- graph_from_adjacency_matrix(props_W$input$adjaMat2, weighted = TRUE)

graph_u <- union(graph1, graph2)
### weight
E(graph_u)$weight <- pmin(E(graph_u)$weight_1, E(graph_u)$weight_2, na.rm = TRUE) # element-wise min. 
graph_u <- delete_edge_attr(graph_u, "weight_1")
graph_u <- delete_edge_attr(graph_u, "weight_2")

set.seed(40)
layout_fr <- layout_with_fr(graph_u, weights = E(graph_u)$weight)
# layout_fr <- layout.forceatlas2(graph_u, iterations=500, plotstep=500,
#                                 gravity = .5, k = 800)

plot_net_u <- props_W
plot_net_u$input$adjaMat1 <- as_adjacency_matrix(graph_u, attr="weight", sparse = FALSE)
```


We plot the results of the netAnalyze function.

```{r, echo=FALSE, fig.height=9, fig.width=16}
phyl_ps_prune <- as.factor(tax_table(ps_Genus_prune)[, 'Phylum'])
names(phyl_ps_prune) <- rownames(tax_table(ps_Genus_prune)[, 'Phylum'])
phylcol <- c(brewer.pal(9, "Set1")[1:7], brewer.pal(9, "Greens")[4], brewer.pal(9,"Set1")[8:9])

phylcol_names <- phylcol[phyl_ps_prune]
names(phylcol_names) <- rownames(tax_table(ps_Genus_prune)[, 'Phylum'])

set.seed(1)

shapeVec <- rep(1, ncol(otu_table(ps_Genus_prune)))
shapeVec[c(116)] <- 2
names(shapeVec) <- names(phyl_ps_prune)

rownames(layout_fr) <- names(phyl_ps_prune)

# plot union graph
# plot(plot_net_u,
#      layout = layout_fr,
#      labels = FALSE,
#      nodeColor = "colorVec",
#      colorVec = phylcol_names,
#      nodeTransp = 40,
#      borderCol = "lightgray", highlightHubs = FALSE,
#      nodeSize = "clr", cexNodes = 1,
#      cexTitle = 1,
#      edgeTranspLow = 30,
#      edgeTranspHigh = 30,
#      nodeShape = c("circle", "triangle"),
#      featVecShape = shapeVec,
#      mar = c(6,5,3,2), groupNames = c("Union (High/Low) graph", "Low PM2.5"))
```

```{r, echo=TRUE, fig.height=9, fig.width=16}
plot_props <- plot(props_W, 
     layout = layout_fr,
     # sameLayout = FALSE, layoutGroup = 1
     labels = FALSE,
     nodeColor = "colorVec",
     colorVec = phylcol_names,
     nodeTransp = 40,
     borderCol = "lightgray", highlightHubs = FALSE, 
     nodeSize = "clr", cexNodes = 1, 
     cexTitle = 2,
     edgeTranspLow = 30, 
     edgeTranspHigh = 30,
     nodeShape = c("circle", "triangle"),
     featVecShape = shapeVec,
     # rmSingles = "inboth",
     mar = c(9,6,4,6), groupNames = c("High PM2.5", "Low PM2.5"))
legend("top", cex = 1.3,
       inset = .035, title = "phylum:",
       legend=levels(phyl_ps_prune), ncol = 2,
       col=phylcol, pt.bg = phylcol, bty = "n", pch=16) 
legend("bottom", 
       inset = .25, cex = 1.3,
       title = "weights:",
       legend=c("+","-"), lty = 1, lwd = 2,
       col=c("darkgreen","red"), bty="n", horiz = TRUE) 
legend("bottom", 
       inset = .35, cex = 1.3,
       title = "differentially abundant:",
       legend=c("Genus"), 
       pch = c(2,0,5), 
       bty="n", horiz = FALSE) 
```


## Network properties

```{r}
summary(props_W)[[1]]
```

#### Vizualisation

```{r, echo = TRUE, fig.height=8, fig.width=16}
nclust_1 <- max(as.numeric(names(table(props_W$clustering$clust1))))+1
nclust_2 <- max(as.numeric(names(table(props_W$clustering$clust2))))+1
nclust <- nclust_1 + nclust_2
col <- sample(polychrome(nclust))

set.seed(13)
plot_cluster <- plot(props_W,
     layout = layout_fr,
     # sameLayout = TRUE, layoutGroup = 1, 
     labels = FALSE, 
     labelFont = 1, cexLabels = 2,
     nodeColor = "cluster",
     colorVec = col,
     sameColThresh = 4,
     nodeTransp = 40, 
     borderCol = "gray40", highlightHubs = FALSE,
     # nodeSize = "clr", cexNodes = 1, 
     nodeShape = c("circle", "triangle"),
     featVecShape = shapeVec,
     # rmSingles = "inboth",
     cexTitle = 1,
     edgeTranspLow = 30, 
     edgeTranspHigh = 30,
     mar = c(6,5,3,2), groupNames = c("High PM2.5", "Low PM2.5"))
legend("bottom", 
       inset = .11, 
       title = "weights:",
       legend=c("+","-"), lty = 1, lwd = 2,
       col=c("darkgreen","red"), bty="n", horiz = TRUE) 
legend("bottom", 
       inset = .17, 
       title = "differentially abundant:",
       legend=c("Genus"),  
       pch = c(2,0,5), 
       bty="n", horiz = FALSE) 
```

#### Shared nodes among modules

```{r, echo = TRUE, message=FALSE}
dat_graph <- data.frame(id = names(props_W$clustering$clust1), 
                        com_p = props_W$clustering$clust1,
                        com_c = props_W$clustering$clust2)

dat_graph[,2] <- paste0(dat_graph[,2], "_P")
dat_graph[,3] <- paste0(dat_graph[,3], "_C")

inc_com_sum <- ddply(data.frame(dat_graph), .(com_p, com_c), 
                     summarise, sum = length(id))

g_sum <- graph.data.frame(inc_com_sum[,c(1,2)], directed = F)
V(g_sum)$type <- V(g_sum)$name %in% inc_com_sum[,1] #the first column of edges is TRUE type

# node size represents the number of OTUs in each module
V(g_sum)$com_nr <- unlist(strsplit(V(g_sum)$name, "_"))[c(TRUE,FALSE)]
V(g_sum)$com_size <- rep(NA, length(V(g_sum)$com_nr))
V(g_sum)$com_size[V(g_sum)$type == TRUE] <- table(props_W$clustering$clust1)[V(g_sum)$com_nr[V(g_sum)$type == TRUE]] # control sizes
V(g_sum)$com_size[V(g_sum)$type == FALSE] <- table(props_W$clustering$clust2)[V(g_sum)$com_nr[V(g_sum)$type == FALSE]] # treated sizes

V(g_sum)$color <- V(g_sum)$type
V(g_sum)$color=gsub("FALSE","#1CFFCE",V(g_sum)$color)
V(g_sum)$color=gsub("TRUE","#66B0FF",V(g_sum)$color)
E(g_sum)$weight <- as.numeric(inc_com_sum[,3])

layout_bi_rows <- layout_as_bipartite(g_sum, hgap = 50, vgap = 60, maxiter = 1000)

legend_cats <- data.frame(size_circle = V(g_sum)$com_size/2,
                          size_text = V(g_sum)$com_size)
legend_cats <- legend_cats[order(legend_cats$size_circle), ]
#dim(legend_cats)
legend_cats <- legend_cats[c(1,25,34),]

# order by vertex size
par(mfrow=c(1,1))
plot(g_sum, vertex.size = V(g_sum)$com_size/2, edge.width=E(g_sum)$weight/5, 
     layout=layout_bi_rows[,2:1], vertex.label=V(g_sum)$com_nr,
     vertex.label.dist=5, vertex.label.degree = pi*V(g_sum)$type, 
     margin = -.2, asp = 2, edge.arrow.size=.7)

legend(x=-2.5, y=-1.1, c("W = 0 (High PM2.5)", "W = 1 (Low PM2.5)"), pch=21,
       col="#777777", pt.bg=c("#66B0FF","#1CFFCE"), pt.cex=2, cex=.8, bty="n", ncol=1)

legend(x=.1, y=-1.1, legend=legend_cats$size_text, pt.cex=legend_cats$size_circle/11, bty="n", cex = .8,
       col="#777777", pch=21, pt.bg="lightgray", ncol = 2, y.intersp = 1.5, x.intersp = 1.5, 
       title = "Module size (nb. of nodes):")
```

#### Zoom connected component

```{r, fig.height=8, fig.width=15}

# deg <- props_W$centralities$degree1
# lcc_names1 <- names(deg[deg != 0])
# 
# deg2 <- props_W$centralities$degree2
# lcc_names2 <- names(deg2[deg2 != 0])
# names_clust <- unique(c(lcc_names1, lcc_names2))

names_clust <- as.character(c(names(props_W$clustering$clust1)[which(props_W$clustering$clust1 %in% c(1,3))],
                           names(props_W$clustering$clust2)[which(props_W$clustering$clust2 %in% c(2,4,5))]))
names_clust <- unique(names_clust)

labels_1 <- unname(tax_table(ps_Genus_prune)[,"Genus"])
labels_1 <- as.character(labels_1)
names(labels_1) <- rownames(tax_table(ps_Genus_prune)[, 'Genus'])

# Rumi
rumi <- grep('Ruminococcaceae', labels_1)
labels_1[rumi] <- paste0("Rumi._",lapply(str_split(labels_1[rumi], "_"), function(x) x[2]))
# Lachno
lac <- grep('Lachnospiraceae', labels_1)
labels_1[lac] <- paste0("Lach._",lapply(str_split(labels_1[lac], "_"), function(x) x[2]))
# Chris
chris <- grep('Christensenellaceae', labels_1)
labels_1[chris] <- paste0("Chris._",lapply(str_split(labels_1[chris], "_"), function(x) x[2]))

# grep("Ruminiclostridium", plot_zoom$q1$Arguments$labels) # 57
# grep("Cloacibacillus", plot_zoom$q1$Arguments$labels)
# grep("Succinivibrio", plot_zoom$q1$Arguments$labels)
# grep("Slackia", plot_zoom$q1$Arguments$labels)
lab_font <- rep(3, length(names_clust))
lab_font[c(30,49,50,57)] <- 4

grep("ella_2", plot_zoom$q1$Arguments$labels)
grep("bacterium", plot_zoom$q1$Arguments$labels)
grep("giella", plot_zoom$q1$Arguments$labels)
grep("Flav", plot_zoom$q1$Arguments$labels)
grep("UCG-003", plot_zoom$q1$Arguments$labels)
grep("lea", plot_zoom$q1$Arguments$labels)
grep("ium_9", plot_zoom$q1$Arguments$labels)
grep("Osci", plot_zoom$q1$Arguments$labels)
grep("Anae", plot_zoom$q1$Arguments$labels)
grep("Tyz", plot_zoom$q1$Arguments$labels)
grep("Chris", plot_zoom$q1$Arguments$labels)
grep("Blautia", plot_zoom$q1$Arguments$labels)
grep("Lachnoclo", plot_zoom$q1$Arguments$labels)
grep("AD3", plot_zoom$q1$Arguments$labels)
lab_pos <- rep(4, length(names_clust)) # right
lab_pos[c(4,16,18,24,25,29,43,62)] <- 1 # bottom
lab_pos[c(2,7,10,12,17,19,21,36)] <- 2 # left
lab_pos[c(14,26,41,46,51)] <- 3 # top

plot_zoom <- p_zoom <- plot(props_W, 
     # sameLayout = TRUE, layoutGroup = 1, 
     layout = layout_fr[rownames(layout_fr) %in% names_clust,], 
     # repulsion = .6,
     labels = labels_1[names_clust],
     # labelFont = 1, 
     cexLabels = 1,
     labelScale = FALSE,
     nodeColor = "colorVec",
     colorVec = phylcol_names,
     sameClustCol = FALSE,
     borderCol = "lightgrey", highlightHubs = FALSE,
     nodeSize = "clr", cexNodes = 1, 
     nodeTransp = 40,
     nodeFilter = "names",
     nodeShape = c("circle", "triangle"),
     featVecShape = shapeVec[names_clust],
     nodeFilterPar = names_clust,
     edgeTranspLow = 30, edgeTranspHigh = 30,
     edgeWidth = .5, cexTitle = 1,
     mar = c(1,2,1,4),
     groupNames = c("", ""),
     labelFont = lab_font,
     node.label.position = lab_pos 
     )
```

```{r}
tax_table(ps_Genus_prune)[c("Seq46","Seq21","Seq56","Seq517","Seq288","Seq11"),]
```

