---
title: "Networks viz Genus (smoking)"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## NetCoMi 

For more details on using the NetCoMi package see <https://github.com/stefpeschel/NetCoMi>.

```{r, echo=FALSE, message=FALSE, warning = FALSE}
library(NetCoMi)
library(metagMisc)
library(phyloseq)
library(igraph)
library(plyr)
library(ForceAtlas2)
library(pals)
library(corrplot)
```

## Networks comparison

The following code was run on a cluster.

```{r, echo = TRUE}
# # load phyloseq data
# load('/n/home05/ajsommer/NetCoMi_cluster/ps_to_net_Gen_smoke.RData')

# gut_split <- metagMisc::phyloseq_sep_variable(ps_Genus_prune, "W")

# net_W <- netConstruct(gut_split$`0`, gut_split$`1`, verbose = 2,
# filtTax = "highestVar",
# filtTaxPar = list(highestVar = 50),
#                            measure = "spieceasi",
#                           measurePar = list(method = "glasso",
#                                             nlambda=20,
#                                             pulsar.params=list(rep.num=50)),
#                           normMethod = "none", zeroMethod = "none",
#                           sparsMethod = "none", seed = 123456, matchDesign = c(1,1))


# props_W <- netAnalyze(net_W, clustMethod = "cluster_fast_greedy")
```

```{r, echo=FALSE}
load('/Users/alicesommer/Desktop/Bureau/DOCTORATE/data_pipeline_microbiome/ps_to_net_Gen_smoke.RData')
load('/Users/alicesommer/Desktop/Bureau/DOCTORATE/data_pipeline_microbiome/props_W_Gen_smoke.RData')
```

We plot the results of the netAnalyze function.

```{r, echo=TRUE, fig.height=9, fig.width=16}
phyl_ps_prune <- as.factor(tax_table(ps_Genus_prune)[, 'Phylum'])
names(phyl_ps_prune) <- rownames(tax_table(ps_Genus_prune)[, 'Phylum'])
phylcol <- rainbow(length(unique(phyl_ps_prune)))

phyl_ps_fam <- as.factor(tax_table(ps_Genus_prune)[, 'Family'])
# names(phyl_ps_fam) <- rownames(tax_table(ps_Genus_prune)[, 'Family'])
labels_phyl <- substr(as.character(phyl_ps_fam), 1, 4)

set.seed(1)

# which(tax_table(ps_Genus_prune)[,"Class"] == "Mollicutes")
# 70 112
# which(tax_table(ps_Genus_prune)[,"Class"] == "Coriobacteriia")
# 28  50  77  87  90  99 110 128 131 >> same numbers for Family Coriobacteriaceae 
# Genus level diff ab
# 24  40  53 105


shapeVec <- rep(1, ncol(otu_table(ps_Genus_prune)))
shapeVec[c(24, 40, 53, 105)] <- 2
shapeVec[c(28,  50,  77,  87,  90, 99, 110, 128, 131, 70, 112)] <- 3
names(shapeVec) <- names(phyl_ps_prune)


plot(props_W, 
     layout = "layout_with_fr",
     sameLayout = TRUE, layoutGroup = 1, 
     labels = FALSE,
     # labelScale = TRUE,
     featVecCol = phyl_ps_prune, nodeColor = "feature",
     nodeTransp = 20,
     borderCol = "gray40", highlightHubs = FALSE, 
     nodeSize = "normCounts", 
     cexNodes = 1, 
     cexTitle = 2,
     edgeTranspLow = 30, 
     edgeTranspHigh = 30,
     nodeShape = c("circle", "triangle","square"),
     featVecShape = shapeVec,
     rmSingles = "inboth",
     mar = c(6,5,3,2), groupNames = c("Smoking", "Non-smoking"))
legend("top", 
       inset = .05, title = "phylum:",
       legend=levels(phyl_ps_prune), ncol = 2,
       col=phylcol, pt.bg = phylcol, bty = "n", pch=16) 
legend("bottom", 
       inset = .11, 
       title = "weights:",
       legend=c("+","-"), lty = 1, lwd = 2,
       col=c("darkgreen","red"), bty="n", horiz = TRUE) 
legend("bottom", 
       inset = .17, 
       title = "differentially abundant:",
       legend=c("Genus (Christensenellaceae-R-7-group)","Class"), pch = c(2,0), 
       bty="n", horiz = FALSE) 
```

## Network properties

```{r}
summary(props_W)[[1]]
```
### Modularity (clusters/modules)

```{r}
summary(props_W)[[2]]
```


#### Vizualisation

```{r, echo = TRUE, fig.height=9, fig.width=16}
nclust_1 <- max(as.numeric(names(table(props_W$clustering$clust1))))+1
nclust_2 <- max(as.numeric(names(table(props_W$clustering$clust2))))+1
nclust <- nclust_1 + nclust_2
set.seed(16)
col <- sample(polychrome(nclust))

set.seed(1)
plot_cluster <- plot(props_W,
     # layout = FA_coord,
     layout = "layout_with_fr",
     sameLayout = TRUE, layoutGroup = 1, 
     labels = FALSE, 
     labelFont = 1, cexLabels = 2,
     nodeColor = "cluster",
     colorVec = col,
     sameColThresh = 2,
     nodeTransp = 40, 
     borderCol = "gray40", highlightHubs = FALSE,
     nodeSize = "fix", cexNodes = 1, 
     nodeShape = c("circle", "triangle", "square"),
     featVecShape = shapeVec,
     rmSingles = "inboth",
     cexTitle = 2,
     edgeTranspLow = 30, 
     edgeTranspHigh = 30,
     mar = c(6,5,3,2), groupNames = c("Smoking", "Non-smoking"))
legend("bottom", 
       inset = .11, 
       title = "weights:",
       legend=c("+","-"), lty = 1, lwd = 2,
       col=c("darkgreen","red"), bty="n", horiz = TRUE) 
legend("bottom", 
       inset = .17, 
       title = "differentially abundant:",
       legend=c("Genus (Christensenellaceae-R-7-group)","Class"), pch = c(2,0), 
       bty="n", horiz = FALSE) 
```

#### Shared nodes among modules

```{r, echo = TRUE, message=FALSE}
dat_graph <- data.frame(id = names(props_W$clustering$clust1), 
                        com_p = props_W$clustering$clust1,
                        com_c = props_W$clustering$clust2)

dat_graph[,2] <- paste0(dat_graph[,2], "_P")
dat_graph[,3] <- paste0(dat_graph[,3], "_C")

inc_com_sum <- ddply(data.frame(dat_graph), .(com_p, com_c), 
                     summarise, sum = length(id))

g_sum <- graph.data.frame(inc_com_sum[,c(1,2)], directed = F)
V(g_sum)$type <- V(g_sum)$name %in% inc_com_sum[,1] #the first column of edges is TRUE type

# node size represents the number of OTUs in each module
V(g_sum)$com_nr <- unlist(strsplit(V(g_sum)$name, "_"))[c(TRUE,FALSE)]
V(g_sum)$com_size <- rep(NA, length(V(g_sum)$com_nr))
V(g_sum)$com_size[V(g_sum)$type == TRUE] <- table(props_W$clustering$clust1)[V(g_sum)$com_nr[V(g_sum)$type == TRUE]] # control sizes
V(g_sum)$com_size[V(g_sum)$type == FALSE] <- table(props_W$clustering$clust2)[V(g_sum)$com_nr[V(g_sum)$type == FALSE]] # treated sizes

V(g_sum)$color <- V(g_sum)$type
V(g_sum)$color=gsub("FALSE","#1CFFCE",V(g_sum)$color)
V(g_sum)$color=gsub("TRUE","#66B0FF",V(g_sum)$color)
E(g_sum)$weight <- as.numeric(inc_com_sum[,3])

layout_bi_rows <- layout_as_bipartite(g_sum, hgap = 50, vgap = 60, maxiter = 1000)

legend_cats <- data.frame(size_circle = V(g_sum)$com_size/2,
                          size_text = V(g_sum)$com_size)
legend_cats <- legend_cats[order(legend_cats$size_circle), ]
# dim(legend_cats)
legend_cats <- legend_cats[c(1,20,24),]

# order by vertex size
par(mfrow=c(1,1))
plot(g_sum, vertex.size = V(g_sum)$com_size/2, edge.width=E(g_sum)$weight/5, 
     layout=layout_bi_rows[,2:1], vertex.label=V(g_sum)$com_nr,
     vertex.label.dist=5, vertex.label.degree = pi*V(g_sum)$type, 
     margin = -.2, asp = 2, edge.arrow.size=.7)

legend(x=-2.5, y=-1.1, c("W = 0 (Smoking)", "W = 1 (Non-smoking)"), pch=21,
       col="#777777", pt.bg=c("#66B0FF","#1CFFCE"), pt.cex=2, cex=.8, bty="n", ncol=1)

legend(x=.1, y=-1.1, legend=legend_cats$size_text, pt.cex=legend_cats$size_circle/11, bty="n", cex = .8,
       col="#777777", pch=21, pt.bg="lightgray", ncol = 2, y.intersp = 1.5, x.intersp = 1.5, 
       title = "Module size (nb. of nodes):")
```

### Module 2 split (smoking)

```{r, fig.height=8, fig.width=15}
names_clust <- as.character(names(which(props_W$clustering$clust1 == 2)))
# labels_phyl <- substr(as.character(phyl_ps_prune[names_clust]), 1, 3)
#col_module <- unique(plot_cluster$q1$Arguments$color[names_clust],
#                     plot_cluster$q2$Arguments$color[names_clust])

plot(props_W, 
     sameLayout = TRUE, layoutGroup = 1, 
     #labels = list(props_W$clustering$clust1[names_clust], props_W$clustering$clust2[names_clust]), 
     labelFont = 1, cexLabels = 1.5,
     nodeColor = "cluster",
     #colorVec =  col_module,
     sameClustCol = FALSE,
     nodeTransp = 40, 
     borderCol = "gray40", highlightHubs = FALSE,
     nodeSize = "fix", cexNodes = 1, 
     nodeFilter = "names",
     nodeShape = c("circle", "triangle", "square"),
     featVecShape = shapeVec[names_clust],
     nodeFilterPar = names_clust,
     edgeTranspLow = 10, edgeTranspHigh = 10,
     groupNames = c("Smoking (module 2)", "Non-smoking"))
```
### Module 1 split (non-smoking)

```{r, fig.height=8, fig.width=15}
names_clust <- as.character(names(which(props_W$clustering$clust2 == 1)))
# labels_phyl <- substr(as.character(phyl_ps_prune[names_clust]), 1, 3)
# col_module <- unique(plot_cluster$q1$Arguments$color[names_clust],
#                     plot_cluster$q2$Arguments$color[names_clust])

plot(props_W, 
     sameLayout = TRUE, layoutGroup = 2, 
     # labels = list(props_W$clustering$clust1[names_clust], props_W$clustering$clust2[names_clust]), 
     labelFont = 1, cexLabels = 1.5,
     nodeColor = "cluster",
     # colorVec =  col_module,
     sameClustCol = FALSE,
     nodeTransp = 40, 
     borderCol = "gray40", highlightHubs = FALSE,
     nodeSize = "fix", cexNodes = 1, 
     nodeFilter = "names",
     nodeShape = c("circle", "triangle","square"),
     featVecShape = shapeVec[names_clust],
     nodeFilterPar = names_clust,
     edgeTranspLow = 10, edgeTranspHigh = 10,
     groupNames = c("Smoking", "Non-smoking (module 1)"))
```

### Correlation structure of module 1 (non-smoking)

```{r, echo = TRUE, fig.height=8, fig.width=15}
col1 <- colorRampPalette(c("#7F0000", "red", "#FF7F00", "yellow", "white",
                           "cyan", "#007FFF", "blue", "#00007F"))

cor_0 <- props_W$input$assoMat1[names_clust,names_clust]
cor_1 <- props_W$input$assoMat2[names_clust,names_clust]

par(mfrow = c(1,2))
corrplot(cor_0, method = "color", tl.col = "grey", mar=c(0,0,5,0),
         col = col1(50), title = "Smoking")
corrplot(cor_1, method = "color", tl.col = "grey", mar=c(0,0,5,0),
         col = col1(100), title = "Non-smoking")
```
